'start:first-time':
  section: general
  editable: yes
  template:
    uk: |
      "Вітаємо!
      Тут ви можете надіслати заявку диспетчеру вашого будинку для попередження про доставку або гостей.
      Але для початку вам потрібно надати інформацію для ідентифікації вас."
    ru: |
      "**Здраствуйте!**
      Здесь вы можете отправить вашу заявку диспетчеру вашего дома для предупреждения о доставке или гостях.
      Но для начала вам необходимо идентифицировать себя."
    en: | 
      "Hello! 
      Here you can send a request to your guard service to warn about delivery or guests. 
      But first you need to provide information to identify you."
  description:
  vars:
  keyboard:
    - - text:
          uk: Почати збір даних для ідентифікації
          ru: Начать идентификацию
          en: Start identification
        data: identification-start

'start:nonidentified':
  section: general
  editable: yes
  template:
    uk: |
      Вітаємо, {name}!
      Тут ви можете надіслати заявку диспетчеру вашого будинку для попередження про доставку або гостей.
      Ми отримали ваші дані та розглянемо ваш запит скоро.
    ru: |
      Дратути, {name}!
    en: |
      Kuku Epta, {name}!
  description:
  vars:
    name:
  keyboard:
    - - text:
          uk: Надіслати дані для ідентифікації ще раз
          ru: <string>
          en: <string>
        data: identification-start

'start:identified':
  section: general
  editable: yes
  template:
    uk: |
        Вітаємо, {name}!
        Тут ви можете надсилати запити диспетчеру вашого будинку для попередження про доставку або гостей.
    ru: |
    en: <string>
  description:
  vars:
    name:
  keyboard:
    - - text:
          uk: Надіслати запит
          ru: <string>
          en: <string>
        data: identification-start

'identification:start':
  section: identification
  editable: yes
  template:
    uk: Введіть, будь ласка, ваше ім'я та прізвище
    ru: 
    en: <string>
  description:
  vars:
  keyboard:

'identification:get-number':
  section: identification
  editable: yes
  template:
    uk: Введіть, будь ласка, ваш мобільний номер телефону в форматі +380*********, або натисніть кнопку відправки вашого контакту.
    ru: 
    en:
  description:
  vars:
  keyboard:
    - - text:
          uk: 📲 Надіслати ваш контакт
          ru:
          en:
        contact: yes

'identification:get-address':
  section: identification
  editable: yes
  template:
    uk: "Будь ласка, напишіть точний номер вашої адреси у форматі: Дім/корпус-квартира\nНаприклад: 15/2-35"
    ru: 
    en:
  description:
  vars:
  keyboard:

'identification:contact-not-valid':
  section: identification
  editable: yes
  template:
    uk: Ви неправильно ввели номер. Спробуйте, будь ласка, ще раз.
    ru: 
    en:
  description:
  vars:
  keyboard:

'identification:address-not-exists':
  section: identification
  editable: yes
  template:
    uk: Ми не знайшли вашу квартиру в нашій базі. Тому не зможемо слідкувати за станом ваших платежів автоматично та оновлювати ваш статус відповідно, що включає вашу можливіть відправляти запити. Запит на ідентифікацію перейде до диспетчеру все рівно та він зможе вас активувати. Активація дає можливість надсилати запити охороні. Але в цілях безпеки статус всех користувачів на початку місяця оновлюється автоматично і, можливо, вам доведеться знову звернутися до диспетчера.
    ru: 
    en:
  description:
  vars:
  keyboard:

'identification:address-success':
  section: identification
  editable: yes
  template:
    uk: Ви успішно надіслали дані для ідентифікації.\nВаші дані будуть перевірені для вашої активації. Вас буде автоматично активовано, якщо впродовж останніх місяців ви сплачували послуги охорони.
    ru: 
    en:
  description:
  vars:
  keyboard:

'identification:address-not-activated':
  section: identification
  editable: yes
  template:
    uk: Поки що ви не зможете надсилати запити охороні, оскільки ви не платили за послуги впродовж останніх місяців.
    ru: 
    en:
  description:
  vars:
  keyboard:

'identification:error':
  section: identification
  editable: yes
  template:
    uk: Сталася помилка при надсиланні даних. Повідомте вашій охороні про це, зазначивши час.
    ru: 
    en:
  description:
  vars:
  keyboard:

'request:intro:undidentified':
  section: request
  editable: yes
  template:
    uk: Вас ще не ідентифіковано. Для додаткової інформації зверніться до диспетчера або надішліть дані знову, надіславши команду /identify
    ru: 
    en:
  description:
  vars:
  keyboard:

'request:intro:unactivated':
  section: request
  editable: yes
  template:
    uk: Вас не було активовано. Можливо, ви забули проплатити послуги охорони за останні місяці.
    ru: 
    en:
  description:
  vars:
  keyboard:

'request:intro:get-request':
  section: request
  editable: yes
  template:
    uk: Напишіть, будь ласка, ціль вашої заявки.
    ru: 
    en:
  description:
  vars:
  keyboard:

'request:confirm':
  section: request
  editable: yes
  template:
    uk: |
      Ви справді бажаєте надіслати запит 
      <i>{body}</i>
      На ваше ім'я {name} та адрес {address}?
    ru: 
    en:
  description:
  vars:
    name:
    address:
  keyboard:
    - - text:
          uk: Так
          ru: <string>
          en: <string>
        data: 'yes'
      - text:
          uk: Ні
          ru: <string>
          en: <string>
        data: 'no'

'request:car-number:get':
  section: request
  editable: yes
  template:
    uk: Додати номер авто до заявки
    ru: 
    en:
  description:
  vars:
  keyboard:
    - - text:
          uk: Без номеру
          ru: <string>
          en: <string>
        data: 'carnumber-cancel'

'request:car-number:confirm':
  section: request
  editable: yes
  template:
    uk: 'Ви справді бажаєте надіслати запит: \n<i>{body}</i>\nНа ваше ім`я {name}, адресу {address} з номером авто {carnumber}?'
    ru: 
    en:
  description:
  vars:
    body:
    name:
    address:
    carnumber:
  keyboard:
    - - text:
          uk: Так
          ru: <string>
          en: <string>
        data: 'yes'
      - text:
          uk: Ні
          ru: <string>
          en: <string>
        data: 'no'

'request:car-number:nonumber':
  section: request
  editable: yes
  template:
    uk: "Ви справді бажаєте надіслати запит:: \n<i>{body}</i>\nНа ваше ім'я {name}, адресу {address} ви не додали номер авто?"
    ru: 
    en:
  description:
  vars:
    body:
    name:
    address:
  keyboard:
    - - text:
          uk: Так
          ru: <string>
          en: <string>
        data: 'yes'
      - text:
          uk: Ні
          ru: <string>
          en: <string>
        data: 'no'

'request:accepted':
  section: request
  editable: yes
  template:
    uk: <b>Ваш запит по адресі {address} був успішно надісланий.</b>
    ru: 
    en:
  description:
  vars:
    address:
  keyboard:

'request:denied':
  section: request
  editable: yes
  template:
    uk: Ви відхилили ваш запит
    ru: 
    en:
  description:
  vars:
  keyboard:

'notify:user-approved':
  section: notifications
  editable: yes
  template:
    uk: <b>Ваш запит на ідентифікацію буде схвалено.</b>
    ru: 
    en:
  description:
  vars:
  keyboard:

'notify:user-denied':
  section: notifications
  editable: yes
  template:
    uk: <b>На жаль, вам відмовлено в ідентифікації.\nВи не зможете надсилати запити охороні.</b> Якщо виникли питання, вам варто звернутися до охорони вашого ЖК.
    ru: 
    en:
  description:
  vars:
  keyboard:

'notify:user-activated':
  section: request
  editable: yes
  template:
    uk: <b>Ви були активовані для надсилання запитів вашій охороні.</b>
    ru: 
    en:
  description:
  vars:
  keyboard:
    - - text:
          uk: Надіслати запит
          ru: <string>
          en: <string>
        data: 'request-start'

'notify:user-deactivated':
  section: request
  editable: yes
  template:
    uk: <b>Ви були деактивовані та не зможете надсилати запити.</b>\nДля запитань, зверніться до охорони вашого ЖК.
    ru: 
    en:
  description:
  vars:
  keyboard:

'notify:request-accepted':
  section: request
  editable: yes
  template:
    uk: "Ми успішно <b>виконали</b> ваш запит №{id}.\n<i>{datetime}</i>\n{body}"
    ru: 
    en:
  description:
  vars:
    id:
    datetime:
    body:
  keyboard:
    - - text:
          uk: Переглянути поточні запити
          ru: <string>
          en: <string>
        data: 'view-requests'
    - - text:
          uk: Надіслати запит
          ru: <string>
          en: <string>
        data: 'request-start'

'notify:request-updated':
  section: request
  editable: yes
  template:
    uk: "Автомобіль за вашим запитом №{id}.\n<i>{datetime}</i>\n{body}\n <b>в'їхав на територію ЖК</b>."
    ru: 
    en:
  description:
  vars:
    datetime:
    body:
  keyboard:

'notify:error':
  section: request
  editable: yes
  template:
    uk: Сталася помилка. Повідомте вашій охороні про це, зазначивши час.
    ru: 
    en:
  description:
  vars:
  keyboard:

'notify:request-unaccepted':
  section: request
  editable: yes
  template:
    uk: "Ваша виконана заявка №{id}.\n<i>{datetime}</i>\n{body}\n\n<b>була щойно позначена як ще не виконана, можливо вона буде виконана через деякий час.</b>"
    ru: 
    en:
  description:
  vars:
    datetime:
    body:
  keyboard:
    - - text:
          uk: Переглянути поточні запити
          ru: <string>
          en: <string>
        data: 'view-requests'
    - - text:
          uk: Надіслати запит
          ru: <string>
          en: <string>
        data: 'request-start'

'notify:request-undenied':
  section: request
  editable: yes
  template:
    uk: Ваш запит, який було відхилено №{id}.\n<i>{datetime}</i>\n{body}\n\n<b> щойно було позначено як ще не виконаний, все ще може бути виконано через для деякий час.</b>
    ru: 
    en:
  description:
  vars:
    datetime:
    body:
  keyboard:
    - - text:
          uk: Переглянути поточні запити
          ru: <string>
          en: <string>
        data: 'view-requests'
    - - text:
          uk: Надіслати запит
          ru: <string>
          en: <string>
        data: 'request-start'

'profile:no-user':
  section: profile
  editable: yes
  template:
    uk: Наразі, у нас немає вашого профілю. Надішліть нам свої дані для ідентифікації /identify
    ru: 
    en:
  description:
  vars:
  keyboard:

'profile:identified:activated':
  section: profile
  editable: yes
  template:
    uk: "Ви авторизовані як:\nІм'я: <b>{firstname}</b>\nПрізвище: <b>{lastname}</b>\nUsername: <b>{username}</b>\nНомер телефону: <b>{phone}</b>Адреса: <b>{address}</b>\nВи ідентифіковані.\nВи оплатили охорону за останні місяці.\nВи можете надсилати запити."
    ru: 
    en:
  description:
  vars:
    firstname:
    lastname:
    username:
    phone:
    address:
  keyboard:
    - - text:
          uk: Змінити мову
          ru: <string>
          en: <string>
        data: 'switch-lang'

'profile:identified:unactivated':
  section: profile
  editable: yes
  template:
    uk: "Ви авторизовані як:\nІм'я: <b>{firstname}</b>\nПрізвище: <b>{lastname}</b>\nUsername: <b>{username}</b>\nНомер телефону: <b>{phone}</b>Адреса: <b>{address}</b>\n \nВи ідентифіковані.\nВи не можете надсилати запити, оскільки не оплатили послуги охорони за останні місяці."
    ru: 
    en:
  description:
  vars:
    firstname:
    lastname:
    username:
    phone:
    address:
  keyboard:
    - - text:
          uk: Змінити мову
          ru: <string>
          en: <string>
        data: 'switch-lang'

'profile:unidentified':
  section: profile
  editable: yes
  template:
    uk: "Ви авторизовані як:\nІм'я: <b>{firstname}</b>\nПрізвище: <b>{lastname}</b>\nUsername: <b>{username}</b>\nНомер телефону: <b>{phone}</b>Адреса: <b>{address}</b> \nВаш запит на ідентифікацію все ще не схвалено."
    ru: 
    en:
  description:
  vars:
    firstname:
    lastname:
    username:
    phone:
    address:
  keyboard:
    - - text:
          uk: Змінити мову
          ru: <string>
          en: <string>
        data: 'switch-lang'

'profile:request-manager:buttons':
  section: profile
  editable: no
  template:
    uk:
    ru: 
    en:
  description:
  vars:
  keyboard:
    - - text:
          uk: Наступна сторінка
          ru: <string>
          en: <string>
        data: 'reqmanage-next-page'
    - - text:
          uk: Попередня сторінка
          ru: <string>
          en: <string>
        data: 'reqmanage-next-page'
    - - text:
          uk: Наступна сторінка
          ru: <string>
          en: <string>
        data: 'reqmanage-next-page'

'profile:request-manager:list':
  section: profile
  editable: no
  template:
    uk: "Список запитів, які все ще у процесі виконання:\n{requests}"
    ru: 
    en:
  description:
  vars:
    requests:
  keyboard:

'profile:request-manager:no-reqs':
  section: profile
  editable: no
  template:
    uk: "Наразі у вас немає активних запитів."
    ru: 
    en:
  description:
  vars:
  keyboard:

'profile:payments:ok':
  section: profile
  editable: yes
  template:
    uk: "Все сплачено."
    ru: 
    en:
  description:
  vars:
  keyboard:

'profile:payments:unpaid':
  section: profile
  editable: yes
  template:
    uk: |
      <b>Ви не сплатили послуги охорони за такі місяці:</b>
      {months}
      Отримати реквізити або оплатити в телеграмі можна за командою /pay

    ru: 
    en:
  description:
  vars:
    months:
  keyboard:

'profile:payments:requisites':
  section: profile
  editable: yes
  template:
    uk: |
      **Реквізити для оплати**
      ТОВ “КОМПЛЕКСНА БЕЗПЕКА СТОЛИЦI ТА ЖИТЛА”
      код ЄДРПОУ <code>43152352</code>
      п/р <code>UA863052990000026005016804997</code>
      ПАТ КБ «Приватбанк»"
    ru: |
      **Реквизиты для оплаты**
      ТОВ “КОМПЛЕКСНА БЕЗПЕКА СТОЛИЦI ТА ЖИТЛА”
      код ЄДРПОУ <code>43152352</code>
      п/р <code>UA863052990000026005016804997</code>
      ПАТ КБ «Приватбанк»"
    en: |
      **Payment requisites**
      ТОВ “КОМПЛЕКСНА БЕЗПЕКА СТОЛИЦI ТА ЖИТЛА”
      код ЄДРПОУ <code>43152352</code>
      п/р <code>UA863052990000026005016804997</code>
      ПАТ КБ «Приватбанк»"
  description:
  vars:
  keyboard:

'profile:lang:choose':
  section: profile
  editable: no
  template:
    uk: "Оберіть бажану мову:"
    ru: 
    en:
  description:
  vars:
  keyboard:
    - - name: "Русский"
        data: "switch-to-russian"
      - name: "Українська"
        data: "switch-to-ukrainian"
      - name: "English"
        data: "switch-to-english"

'profile:lang:changed':
  section: profile
  editable: no
  template:
    uk: "Ви змінили мову на українську"
    ru: 
    en:
  description:
  vars:
  keyboard:
