version: "3.3"

services: 
  redis:
    build: 
      context: .
      dockerfile: build/redis.Dockerfile
    ports:
      - 6379:6379

  postgres:
    image: postgres:15
    env_file:
      - .env
    ports: 
      - 5432:5432
  
  oms:
    build:
      context: ./services/oms/
      dockerfile: Dockerfile
    depends_on: 
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - ./services/oms/server:/main
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      POSTGRES_HOST: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_SSLMODE: disable
      PORT: 9876
      MIGRATE_VERSION: 5
      ENVIRONMENT: development
    ports: 
      - 9876:9876

  # worker:
  #   build:
  #     context: ./services/worker
  #     dockerfile: Dockerfile
  #   restart: no
  #   volumes:
  #     - ./keys/worker/credentials.json:/credentials.json
  #     - ./configs/worker/config.yml:/config.yml
  #     # - <executable>:<executable>
  #   depends_on:
  #     - redis
  #     - database
  #   env_file:
  #     - .env

  telegram-bot:
    build:
      context: ./services/telegram-bot
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      GRPC_URL: oms:9876
    volumes: 
      # - ./<executable>:/main
      - ./services/telegram-bot/main:/main
      - ./configs/telegram-bot/config.json:/config.json
      - ./configs/telegram-bot/sigma-config.yml:/sigma-config.yml
    depends_on:
      - oms

  api:
    build:
      context: ./services/api/
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - WEB_PORT=3000
      - GRPC_URL=oms:9876
      - DOMAIN=localhost
      - STAGE=dev
    volumes:
      - ./services/api/src:/app/src
      - ./services/api/gen:/app/gen
      - tables:/app/tables
    depends_on:
      - oms
    ports:
      - 3001:3000

  frontend:
    build: 
      context: ./services/frontend/
      dockerfile: Dockerfile
      target: development
    environment:
      API_HOST: api
      API_PORT: 3000
      PORT: 8000
    volumes: 
      - ./services/frontend:/app
    depends_on:
      - api
    ports:
      - 8000:8000
      - 2019:2019

volumes: 
  tables:
  caddy_data:
    # external: true
  caddy_config:
