---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
data:
  redis-config: |
    appendonly no
    save 600 1
    dir /data
    maxmemory 100mb
    maxmemory-policy noeviction
    loglevel warning
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  BOT_TOKEN: 830576128:AAFOlretyYkbAUEOcWB6hGcC0fOHEf9NTic
  WEB_PORT: "3000"
  POSTGRES_DB: postgres
  POSTGRES_HOST: "10.96.0.3"         # Here can be another addr
  POSTGRES_PASSWORD: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_URL: postgres://postgres:postgres@database/postgres?sslmode=disable
  POSTGRES_USER: postgres
  WORKER_REDIS_ADDRESS: 10.96.0.2:6379  # Here can be another addr
  WORKER_REDIS_DB: "0"
  WORKER_REDIS_PASSWORD: ""
  MIGRATE_VERSION: "5"
  ENVIRONMENT: "development"


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bot-config
data:
  config.json: |
    {
        "debug": false,
        "tg-debug": false,
        "payment-threshold": 50,
        "vin": true,
        "components": {
            "identification": true,
            "payment": false,
            "manage-requests": true,
            "request": true
        },
        "sigma": {
            "use-redis": true,
            "populate-on-start": false
        }
    }

