---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup-cron-job
spec:
#Cron Time is set according to server time, ensure server time zone and set accordingly.
  schedule: "0 */12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: pgsql-backup
            image: registry.gitlab.com/m11259/postgre-backup:latest
            envFrom:
            - configMapRef:
                name: env-config
            volumeMounts:
            - mountPath: "/pg_backup"
              name: backup-volume
          volumes:
            - name: backup-volume
              persistentVolumeClaim:
                claimName: pg-backup-pvc
      backoffLimit: 3
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-backup-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi