# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: / spec:
#       rules:
#       - http:
#           paths:
#           - path: /
#           pathType: Prefix
#           backend:
#             service:
#             name: app-service
#             port:
#               number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: izum-redis-service
spec:
  clusterIP: 10.96.0.2
  selector:
    product: izum
    type: redis
  ports:  
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
apiVersion: apps/v1

kind: Deployment

metadata:
  name: izum-redis
  labels:
    product: izum
    type: redis

spec:
  replicas: 1
  selector:
    matchLabels:
      product: izum
      type: redis
  template:
    metadata:
      labels:
        product: izum
        type: redis
    spec:
      containers:
      - name: izum-redis
        image: redis:alpine
        command:
          - redis-server
          - "/usr/local/etc/redis/redis.conf"
        envFrom:
        - configMapRef:
            name: env-config
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: "/usr/local/etc/redis/redis.conf"
          name: config
      volumes:
        - name: config
          configMap:
            name: redis

      restartPolicy: Always
